services:
  - type: web
    name: bankapp-backend
    env: java
    plan: free
    region: oregon
    branch: main
    rootDir: bankapp
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
