services:
  - type: web
    name: bankapp-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    rootDir: bankapp
    dockerfilePath: ./bankapp/Dockerfile
    dockerContext: ./bankapp
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
